name: Security Vulnerability
description: Report a security vulnerability in Go OpenAPI Validator
title: "[SECURITY] "
labels: ["security", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Please note**: For security vulnerabilities, prefer using the private vulnerability reporting feature via the Security tab instead of creating a public issue.
        If you must use this template, the issue will be immediately locked and made private.

  - type: textarea
    attributes:
      label: Description of the vulnerability
      description: A clear and concise description of what the vulnerability is.
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Affected version
      description: What version of the boilerplate are you running?
      options:
        - 1.0.0 (Default)
      default: 0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: List steps to reproduce the vulnerability.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested fix / mitigation
      description: Any ideas on how to fix or mitigate this issue?

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
