name: "Run Go tests (composite)"
description: "Composite action to run Go tests and upload coverage to Codecov"
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.5'

    - name: Get dependencies
      run: go mod download
      shell: bash

    - name: Run tests with coverage
      run: |
        set -euo pipefail
        # Exclude packages under the examples directory from coverage
        PKGS=$(go list ./... | grep -v '/examples' | tr '\n' ' ')
        if [ -z "$PKGS" ]; then
          echo "No packages found to test"
          exit 0
        fi
        echo "Testing packages: $PKGS"
        go test $PKGS -covermode=count -coverprofile=coverage.out
      shell: bash

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.out
        flags: unittests
        fail_ci_if_error: true
        verbose: true
